name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push of Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/fakeshop:latest
            ${{ vars.DOCKERHUB_USERNAME }}/fakeshop:v${{ github.run_number }}

  CD:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    needs: [CI]
    steps:
      - name: Get Project Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: KubeCTL Configure
        run: aws eks update-kubeconfig --name challenge-k8s

      - name: Deploy Kubernetes Manifest
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/fakeshop:v${{ github.run_number }}
